# application: google.com:angulardart
application: kw-angulardart
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "10m"

handlers:
- url: /favicon\.ico
  static_files: _site/img/favicon.ico
  upload: _site/img/favicon.ico

- url: /(.*\.png)
  static_files: _site/\1
  expiration: 1d
  upload: _site/(.*\.png)

- url: /(.*\.ico)
  static_files: _site/\1
  expiration: 7d
  upload: _site/(.*\.ico)

- url: /(.*\.jpg)
  static_files: _site/\1
  expiration: 1d
  upload: _site/(.*\.jpg)

- url: (.*)/
  static_files: _site\1/index.html
  upload: _site/index.html

- url: (.*\..*)
  static_files: _site\1
  upload: _site